name: othala
description: Othala app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`.
publish_to: 'none'

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # Utility plugins
  http: ^0.13.4
  date_format: ^2.0.6
  intl: ^0.17.0

  # File/storage plugins
  flutter_secure_storage: ^6.0.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  path: ^1.8.0
  path_provider: ^2.0.11

  # UI/Component plugins
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.1
  flutter_svg: ^1.0.3
  page_view_indicators: ^2.0.0
  flutter_emoji:
    git: https://github.com/cek-cek/flutter-emoji
  flutter_staggered_grid_view: ^0.4.0
  # qr_flutter 4.0.0 contains outdated package:qr/qr.dart with error.
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git
  qr_code_scanner: ^1.0.0

  # bitcoin
  bitcoin_dart:
    git:
      url: https://github.com/saentari/bitcoin_dart.git
  btc_address_validate:
    git:
      url: https://github.com/saentari/btc_address_validate.git
  dart_lnurl:
    git:
      url: https://github.com/saentari/dart_lnurl.git


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

  # Flutter Launcher Icons is a command-line tool which simplifies the task
  # of updating your Flutter app's launcher icon.
  flutter_launcher_icons: ^0.9.3
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"
  adaptive_icon_background: "#000000"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  # Custom fonts used by the application.
  fonts:
    - family: Rajdhani
      fonts:
        - asset: fonts/Rajdhani-Light.ttf
          weight: 300
        - asset: fonts/Rajdhani-Regular.ttf
          weight: 400
        - asset: fonts/Rajdhani-Medium.ttf
          weight: 500
        - asset: fonts/Rajdhani-SemiBold.ttf
          weight: 600
        - asset: fonts/Rajdhani-Bold.ttf
          weight: 700
